### ISSUE TITLE
Bulk Domain Transfer

### ISSUE THREAD

**Issue by tomh134** [godaddy/wp-reseller-store#97]
Currently, i see there is functionality to allow for single domain transfer.

> Domain Transfer [rstore_domain_transfer]

 However, can we also add the bulk domain transfer functionality, please? This seems to be available in the Godaddy's own hosted platform so thought would also be within the WP plugin? 

Thanks.

**Comment by cberesford-godaddy** [comment]
Hi @tomh134 - I would recommend creating a navigation item on your site and linking to a page such as https://www.secureserver.net/domains/bulk-domain-transfer.aspx?plid=1592 (using your unique PLID instead of 1592). We don't currently have a bulk transfer shortcode. Apologies for the delays in responding to this issue. I will mark this as resolved, but please let me know if additional questions arise. Thanks and have a nice day!
